### ISSUE TITLE
Attach files to a topography

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#547] opened 2020-11-09 11:31 UTC
>   * Feature request: We should be able to store an image file with all
>     of the TEM images.
>       o Ideal would be to store it in the raw format (.dm3) which
>         contains useful metadata.
>       o Second-best would be to store it as an image file (.tif)
> 
> Yes, general attachments are on the todo list. We should support adding 
> any type of file, maybe up to a certain size.

Do you mean, you want to attach additional multiple files to a topography?

**Comment by pastewka** [comment] 2020-11-09 16:08
Yes, that's the idea.

**Comment by pastewka** [comment] 2020-11-09 16:09
Note that #331 looks like a duplicate of this.

**Comment by pastewka** [comment] 2022-03-07 14:21
Discussion with @tdbjacobs: Flat structure (no subdirectories), but multiple files. Should be include in ZIP download.

**Comment by tdbjacobs** [comment] 2022-07-27 16:55
@pastewka , @mcrot : Can I request to prioritize this enhancement? We are running into problems where people are asking to see the TEM images for our data (not just the raw (x,y) coordinates of our traced points.

**Comment by pastewka** [comment] 2022-07-27 17:06
Is this more important than #173 ?

**Comment by tdbjacobs** [comment] 2022-07-27 17:08
While I would like to say yes. The answer is no.

The vast majority of groups need 173 far more than 547!

Best,
Tevis

**Closed** 2024-10-23 20:11 UTC
Labels: enhancement
