### ISSUE TITLE
Add co-ownership or ability to transfer ownership

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#939] opened 2022-12-06 20:11 UTC
Ideally, I'd like to add co-ownership for surfaces. If that's not possible, then I'd like to add the capability to transfer ownership of a surface. 

This is particularly important when a student or worker leaves a group or company and the remaining coworkers cannot share/modify the image. 

(I can't remember if we already have an issue for this or not. Apologies if it's a duplicate)

**Comment by pastewka** [comment] 2022-12-06 21:07
Duplicate of #706

**Closed** 2023-06-02 13:38 UTC
