### ISSUE TITLE
Incorrect Scaling for OPD Files

### ISSUE THREAD

**Issue by megannescio** [ContactEngineering/TopoBank#674] opened 2021-05-28 15:32 UTC
The OPD files from the Bruker profilometer give a height scale that is different from what is made from the contact engineering website. 
![1a](https://user-images.githubusercontent.com/83083564/120007880-654eb500-bfa8-11eb-865b-7a6807fc14a6.PNG)

**Comment by pastewka** [comment] 2021-05-31 05:07
Hi @megannescio - can you share that topography with me? I'll check what's going on.

**Comment by mcrot** [comment] 2021-06-14 12:17
This is a duplicate of #675, which is fixed. The fix will be available when the next release 0.13.0 is online. Closing.

**Closed by mcrot** 2021-06-14 12:17 UTC
