### ISSUE TITLE
Incorrect Scaling for OPD files

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/TopoBank#675] opened 2021-06-02 14:26 UTC
Hi,
Adding on to earlier github post on the incorrect scaling with OPD files, here is my experience with the issue:
![image](https://user-images.githubusercontent.com/78487900/120497634-922a1000-c38c-11eb-814c-bf884d3c1325.png)

@tdbjacobs 

I am unable to manually correct the height scaling on this data file either. I have shared the surface with you @pastewka 

Thank you!

**Comment by tdbjacobs** [comment] 2021-06-02 14:37
Hey Lars and Michael,

This is a somewhat urgent problem because the data/analysis of the webapp
is incorrect.

Can we prioritize this fix?

-Tevis




Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***

**Comment by pastewka** [comment] 2021-06-02 14:40
Duplicate of #674

**Comment by pastewka** [comment] 2021-06-02 15:07
@mcrot - this looks to be a bug on the `TopoBank` end. I just opened and plotted the file in `SurfaceTopography` and the height scaling looks correct.

![image](https://user-images.githubusercontent.com/2530391/120504985-ddf8ab80-c3c4-11eb-9fe9-1edda5d58605.png)

Steps to reproduce:
```python
import matplotlib.pyplot as plt
from SurfaceTopography import read_topography
t = read_topography('op.dr_psi_5x_pr.013.OPD')
t.plot()
plt.show()
```

**Comment by pastewka** [comment] 2021-06-02 15:11
It looks like `TopoBank` is using the wrong scale factor. It uses 1, which it  should be 0.0005343980102539062 for this particular surface:

![image](https://user-images.githubusercontent.com/2530391/120505688-8149c080-c3c5-11eb-967c-1bdcb45b93bd.png)

If I set it to 1 I get the same image as the web site:

![image](https://user-images.githubusercontent.com/2530391/120505475-4d6e9b00-c3c5-11eb-80ca-8a6880047d52.png)

**Comment by pastewka** [comment] 2021-06-02 15:12
It's already wrong in the upload form. The height conversion factor should be fixed (not editable) since it is contained in the data file. It also should not be 1.

![image](https://user-images.githubusercontent.com/2530391/120505946-c3730200-c3c5-11eb-8f38-a15c09a22f45.png)

**Comment by mcrot** [comment] 2021-06-07 08:06
Hi all, thanks for the analysis. I'm prioritizing this issue and work for a fix.

**Comment by mcrot** [comment] 2021-06-07 09:04
For determining the height scale factor from the file, so far I'm using the `info` dict of the reader object. Here for example for
DI files:
```python
In [12]: r_di = open_topography('gain_control_uncd_7.001')
In [13]: r_di.default_channel.info
Out[13]: 
{'acquisition_time': '2016-05-26 22:30:13',
 'unit': 'nm',
 'height_scale_factor': 0.10560192472686768}
```
For the given OPD file, this information is missing:
```python
In [17]: r_opd = open_topography(r'/home/michael/work/imtek/data/Optical Profilometre/op.dr_psi_5x_pr.013.OPD')
In [18]: r_opd.default_channel.info
Out[18]: {'unit': 'mm'}
```
For me it seems to be missing in `SurfaceTopography` (version 0.93.1.dev29+gad6d5aff.d20210607).
How to access it instead?

**Comment by mcrot** [comment] 2021-06-07 09:23
I think this can be easily added to the reader in `SurfaceTopography`. I'm preparing a PR, let me know if you have any objections. For the automated tests, it would be good to have an OPD file which I can use in the public repository for the tests.
It should have these characteristics:

- included physical sizes
- included height scale factor 
- as small as possible; `op.dr_psi_5x_pr.013.OPD` has about 200kB, this is okay, even smaller would be good

**Comment by mcrot** [comment] 2021-06-07 09:28
It seems like for the tests I can already use the OPD files we already have. However, a smaller test file would be great, but is not urgent.

**Comment by pastewka** [comment] 2021-06-07 10:05
I think all OPDs have that height factor. You can also check whether the reader returns a scaled topography (in which case it has that factor) or not (in which case it is missing).

**Comment by mcrot** [comment] 2021-06-07 10:11
It seems like the reader always returns a scaled topography, if the factor is not given, it is calculated. See #99.
We currently discuss there whether we should always automatically add the `height_scale_factor`to the info dict as soon
as `scale` is called, then this cannot happen for other file formats.

**Comment by mcrot** [comment] 2021-06-14 10:05
This is fixed now and will be available in the next release, probably today or tomorrow.

**Closed** 2021-06-14 10:04 UTC
Labels: bug
