### ISSUE TITLE
Links to analysis functions

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/topobank#824] opened 2022-03-16 14:43 UTC
It would be nice to encode the analysis function in the URL, so that we can directly send the view by sending a link

![grafik](https://user-images.githubusercontent.com/40853209/158615968-6cf05ec9-57aa-40f0-9ecd-a899b319f8b6.png)

https://contact.engineering/analysis/function/17/

But if someone else (or my other browser) opens this link he gets: 

![grafik](https://user-images.githubusercontent.com/40853209/158616167-b1bd4f87-afa1-4b35-ab7a-bdffad4cbaec.png)

**Comment by mcrot** [comment] 2022-04-21 13:09
Yes, the problem is, that we would need to encode the selection also in the URL. This could become quite
complex, maybe we can have a hash for each selection which can be referenced in the URL, e.g.

 https://contact.engineering/analysis/select/asdh37d/function/17/
 
Then we would need to keep a permanent list of selections in the database in order to resolve future requests.
However, it is referred as a good practice to always resolve URLs the same way.

**Comment by pastewka** [comment] 2022-04-21 15:05
This is not crucial. There are other things that need fixing before this. Please move to post v1.0

**Comment by pastewka** [comment] 2023-04-29 16:24
This would be possible if we switched the route from POST to GET. However, there is a dictionary that is passed in the POST request that seems a bit tedious (but not impossible) to serialize.

**Comment by pastewka** [comment] 2023-05-15 19:16
Closed by #965

**Closed by pastewka** 2023-05-15 19:16 UTC
Labels: enhancement, nice to have
